### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by max-te** [mmatyas/pegasus-frontend#559]
I'm trying to create a metadata file for my native Linux games. So I started out with a pretty simple metadata.pegasus.txt file inside my games directory:

```yaml
collection: Native
launch: bash "{file.path}"
files:
    Moonlighter/start.sh

game: Moonlighter
file: Moonlighter/start.sh
```

But with this I end up with pegasus stuck at the loading screen, displaying '0 games found'. Nothing notable appears in the log:
```
[i] Program settings loaded
[i] Pegasus alpha13-11-gf379dfe (2019-10-17)
[i] Running on Arch Linux (x86_64, xcb)
[i] Found locale `de`
[i] Found locale `en`
[i] Found locale `es`
[i] Found locale `fr`
[i] Found locale `hu`
[i] Found locale `ko`
[i] Found locale `pt-BR`
[i] Found locale `ru`
[i] Locale set to `en`
[i] Found theme 'Pegasus Grid' (`:/themes/pegasus-theme-grid/`)
[i] Theme set to 'Pegasus Grid' (`:/themes/pegasus-theme-grid/`)
[i] Gamepad: connected device 0x28e (generic)
[i] Metafiles: found `/home/max/Games/metadata.pegasus.txt`
[i] Closing Pegasus, goodbye!
```
If instead I put something like this in `.config/pegasus-frontend/metafiles`, that works fine:
```yaml
collection: Native
launch: bash "{file.path}"
files:
    /home/max/Games/Moonlighter/start.sh

game: Moonlighter
file: /home/max/Games/Moonlighter/start.sh
```
I suspect pegasus is trying to scan my games directory for _something_, which is desirable for rom collections, but in case of my games folder it will probably trip over some symlink or just be really slow because some games just have a lot of files. I would still prefer to have the metadata in the games folder for portability.
